###

POST http://localhost:3000/register 
Content-Type: application/json

{
"Firstname": "Mridul",
"Lastname":"Dhiman",
"Email": "demoemail@gmail.com",
"Password":"1234",
"registerOption": "1",
}


###

###


GET http://localhost:3000/booking


###


GET http://localhost:3000/users

###

DELETE http://localhost:3000/users

###

DELETE http://localhost:3000/users/65c11f29cf667911ae41259f

###

GET http://localhost:3000/users/65964a872e3fe6c5bf10e326

### 

 
GET http://localhost:3000/users/approved/registered

###
 
GET http://localhost:3000/users/approved/pending

###


DELETE http://localhost:3000/users/approved/registered/65b7701c6cdb971024d4e877


###

  
DELETE http://localhost:3000/users/approved/pending/65b56c16d56a83e936fcdd82

###

DELETE http://localhost:3000/users/approved/registered/659bf94df3fba23f2b5b7daa

###

GET http://localhost:3000/users/65964a872e3fe6c5bf10e326/bookingHistory/upcoming


###

POST http://localhost:4000/admin/approveRegistration
Content-Type: application/json

{
    "user": "653a988078d11f8a414073a1",
    "status":"accept"
}


### 


POST http://localhost:4000/admin/approveRegistration
Content-Type: application/json

{
"user":"6539800af09eae409fd99fd3",
"status": "reject"
}



### 

GET http://localhost:4000/login/admin

###

  
GET http://localhost:3000/login

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "Email" : "ritikd.cs.23@nitj.ac.in",
    "Password": "1234"
}


### create admin
 
POST http://localhost:3000/login/admin
Content-Type: application/json

{
    "email": "avirals.cs.22@nitj.ac.in",
    "password": "1234",
    "isAdmin": true,
    "isMainAdmin": "false"
}


###

DELETE http://localhost:3000/login

###

DELETE http://localhost:3000/login/65b5481704a523b0b6075dd1


### 

GET http://localhost:4000/users/approved/pending/length


### 

GET http://localhost:4000/references

###

DELETE http://localhost:3000/admin/bookingApproval

###

GET http://localhost:4000/references/type/student

###

GET http://localhost:4000/references/type/faculty

###

GET http://localhost:4000/references/type/alumni    


###

GET http://localhost:3000/email

###



###


GET http://localhost:3000/booking 

### 

GET http://localhost:3000/booking/approved/cancelled


###


DELETE http://localhost:3000/booking

###
 
DELETE http://localhost:3000/booking/65c5ffde82e2a077f4290597


###

 
POST http://localhost:3000/guestHouse


###

DELETE http://localhost:3000/guestHouse

###
    
GET  http://localhost:3000/guestHouse

###


GET http://localhost:3000/admin/bookingApproval

###


POST http://localhost:4000/admin/bookingApproval
Content-Type: application/json

{
    "booking" : "6559ae6485522d45e4d41a89",
    "status" : "accept",
    "roomsAllotted" : ["8", "9"],
    "guestHouseAllotted" : "1"
}


###

GET  http://localhost:3000/booking/approved/upcoming


### 



POST http://localhost:4000/login/forgot-password
Content-Type: application/json

{
    "email" : "mriduld.cs.21@nitj.ac.in"
}


###


POST http://localhost:4000/login/update-password 
Content-Type: application/json

{
    "email": "mriduld.cs.21@nitj.ac.in",
    "password" : "nitj"
}

###

POST http://localhost:3000/email/booking/hod
Content-Type: application/json

{
    "name": "Mridul Dhiman",
    "roll": "21103096"
}

###
  
POST  http://localhost:3000/booking/register 
Content-Type: application/json

{
    "visitType": "official",
    "purpose": "Seminar conduction",
    "firstName" : "Vikas",
    "lastName" : "Jaglan",
     "guestHouseSelected": "1",
     "roomsSelected" : "2",
    "designation": "Professor at IIT Roorkee",
    "address": "Benaras, UP",
    "phNumber": "12345678",
    "email": "chakshud21@gmail.com",
    "companion1": "Dr. Subramanium",
    "companion2" : "Dr. Srinivasan",
    "companion3" : "Dr. Venky Nair",
      "bookingFor": "myself",
      "arrivalDate" : "2024-11-01",
      "departureDate" : "2024-11-03",
        "isAdmin" : false,
    //   "isStudent" : "true",
    #  "PersonDept": "CSE",
    "Person"
      "PersonName": "Demo Person",
        "PersonEmail": "mriduld.cs.21@nitj.ac.in"
}