###

POST http://localhost:4000/register 
Content-Type: application/json

{
"Firstname": "xyz",
"Lastname":"adf",
"Phnnumber":"7347652278",
"Email":"j69@nx.com",
"Password":"xyz",
"Address": "asfdasadfadsfd, UP",
"selectedOption": "student",

}



###


GET http://localhost:4000/users

###

GET http://localhost:4000/users/65490307b69c78423f779fe6

### 


GET http://localhost:4000/users/approved/registered

###

GET http://localhost:4000/users/6545eecab7f0c070a5456b17/bookingHistory


###


GET http://localhost:4000/users/approved/rejected

###

POST http://localhost:4000/admin/approveRegistration
Content-Type: application/json

{
    "user": "653a988078d11f8a414073a1",
    "status":"accept"
}


### 


POST http://localhost:4000/admin/approveRegistration
Content-Type: application/json

{
"user":"6539800af09eae409fd99fd3",
"status": "reject"
}



### 

GET http://localhost:4000/login/admin

###


GET http://localhost:4000/login


### 

GET http://localhost:4000/users/approved/pending/length


### 

GET http://localhost:4000/references

###

GET http://localhost:4000/references/type/student

###

GET http://localhost:4000/references/type/faculty

###

GET http://localhost:4000/references/type/alumni    


###

GET http://localhost:4000/email

###


POST  http://localhost:4000/booking/register 
Content-Type: application/json

{
    "visitType": "official",
    "purpose": "Seminar conduction",
    "firstName" : "Vikas",
    "lastName" : "Jaglan",
     "guestHouseSelected": ["1", "1"],
     "roomSelected" : ["8", "9"],
    "designation": "Professor at IIT Roorkee",
    "address": "Benaras, UP",
    "phNumber": "12345678",
    "email": "chakshud21@gmail.com",
    "companion1": "Dr. Subramanium",
    "companion2" : "Dr. Srinivasan",
    "companion3" : "Dr. Venky Nair",
      "bookingFor": "myself",
      "arrivalDate" : "2023-11-01",
      "departureDate" : "2023-11-03",
    "roomBooker" : {
        "name": "Mridul",
        "designation":"Student at Nitj",
        "dept": "CSE",
        "phone": "923452355",
        "email": "dhimanmridul91@gmail.com",
        "address": "Baijnath, Himachal"
    }
}



###

GET http://localhost:4000/booking 


###


POST http://localhost:4000/guestHouse


###
    
GET  http://localhost:4000/guestHouse

###

POST http://localhost:4000/admin/bookingApproval
Content-Type: application/json

{
    "booking" : "65440ea741afe49f90c5aea9",
    "status" : "accept",
    "roomAllotted" : ["3", "3"],
    "guestHouseAllotted" : ["1" , "2"]
}


###


GET  http://localhost:4000/booking/approved/approved
